/**
 * legacy-import.template-roundtrip.test.ts
 *
 * Integration tests that validate the CSV template generated by
 * `buildTemplateCsv()` (shared/legacyFamiliasTypes.ts) against the full
 * parser pipeline (parseCSVLine → fieldsToLegacyRow → parseRow →
 * assembleFamilyGroups).
 *
 * These tests pin two contracts:
 *   1. The template itself is parseable with 0 hard errors and 0 group errors.
 *   2. A realistic multi-family CSV (3 families, titular + member) also parses
 *      cleanly — smoke-testing the full import flow with representative data.
 *
 * No mocks. No DB calls. Pure deterministic pipeline.
 */
import { describe, it, expect } from "vitest";
import { buildTemplateCsv, CSV_HEADERS } from "../../../csvLegacyFamiliasMapper";
import { parseRow } from "../../../csvLegacyFamiliasMapper";
import { fieldsToLegacyRow, resolveColumnMap } from "../../../csvLegacyFamiliasParser";
import { assembleFamilyGroups } from "../../../csvLegacyFamiliasGroup";
import { parseCSVLine } from "../../announcements/_shared";

// ---------------------------------------------------------------------------
// Shared helper: same transformCsv used in legacy-import.test.ts
// (duplicated here intentionally to keep this file self-contained and avoid
// coupling to the sibling test file's internal helpers)
// ---------------------------------------------------------------------------
function transformCsv(csv: string): {
  groups: ReturnType<typeof assembleFamilyGroups>;
  parseErrors: number;
} {
  const csvNormalised = csv
    .replace(/^\uFEFF/, "") // strip BOM
    .replace(/\r\n/g, "\n")
    .replace(/\r/g, "\n");
  const lines = csvNormalised.split("\n");

  let headerLineIdx = -1;
  for (let i = 0; i < lines.length; i++) {
    const fields = parseCSVLine(lines[i]);
    if (fields[0]?.trim().startsWith("NÚMERO DE ORDEN")) {
      headerLineIdx = i;
      break;
    }
  }
    if (headerLineIdx === -1) throw new Error("Header not found in CSV");
  // Build column map from the actual header line
  const headerFields = parseCSVLine(lines[headerLineIdx]).map((f) => f.trim());
  const columnMap = resolveColumnMap(headerFields);
  let dataStart = headerLineIdx + 1;
  const next = parseCSVLine(lines[headerLineIdx + 1] ?? "");
  if (next[0]?.trim().startsWith("(MARCAR CON UNA X")) {
    dataStart = headerLineIdx + 2;
  }
  const cleanRows = [];
  let parseErrors = 0;
  for (let i = dataStart; i < lines.length; i++) {
    if (!lines[i].trim()) continue;
    const fields = parseCSVLine(lines[i]).map((f) => f.trim());
    if (!fields[1]) continue;
    const legacy = fieldsToLegacyRow(fields, columnMap);
    const r = parseRow(legacy, i + 1);
    if (r.ok) cleanRows.push(r.row);
    else parseErrors++;
  }
  return { groups: assembleFamilyGroups(cleanRows), parseErrors };
}

// ---------------------------------------------------------------------------
// Test 1: Template roundtrip — 0 parse errors, 0 group errors
// ---------------------------------------------------------------------------
describe("buildTemplateCsv() → full parser pipeline", () => {
  it("produces a CSV that parses with 0 hard errors and 0 group errors", () => {
    const csv = buildTemplateCsv();
    const { groups, parseErrors } = transformCsv(csv);

    expect(parseErrors).toBe(0);
    expect(groups.length).toBe(1);
    expect(groups[0].errors).toHaveLength(0);
  });

  it("template row is recognised as a titular (CABEZA DE FAMILIA = x)", () => {
    const csv = buildTemplateCsv();
    const { groups } = transformCsv(csv);

    expect(groups[0].rows[0].is_titular).toBe(true);
    expect(groups[0].titular_index).toBe(0);
  });

  it("template header has exactly 19 columns matching CSV_HEADERS", () => {
    const csv = buildTemplateCsv();
    const headerLine = csv.split("\n")[0];
    const columns = parseCSVLine(headerLine);

    expect(columns).toHaveLength(CSV_HEADERS.length);
    expect(columns).toHaveLength(19);
    expect(columns[0]).toBe("NÚMERO DE ORDEN");
    expect(columns[1]).toBe("NUMERO FAMILIA BOCATAS");
    expect(columns[8]).toBe("CABEZA DE FAMILIA");
    expect(columns[18]).toBe("Otras Características");
  });
});

// ---------------------------------------------------------------------------
// Test 2: Smoke test — 3 realistic families (titular + member) parse cleanly
// ---------------------------------------------------------------------------
describe("Smoke test: 3 realistic families with titular + member rows", () => {
  /**
   * Three families:
   *   - Familia 201: titular (DNI) + esposa (NIE)
   *   - Familia 202: titular (NIE) solo
   *   - Familia 203: titular (Pasaporte) + hijo
   *
   * All values use formats accepted by the parser. Warnings are allowed
   * (e.g. coerced situacion_laboral) but hard errors must be 0.
   */
  // Build header from CSV_HEADERS so this fixture stays in sync if columns change.
  const HEADER = CSV_HEADERS.map((h) => `"${h}"`).join(",");

  const REALISTIC_CSV = [
    HEADER,
    // Familia 201 — titular
    '1,201,10/01/2023,Carlos,García López,M,611000001,55307681H,x,España,15/06/1980,carlos@test.es,"Calle Alcalá 5",28001,Madrid,"Familia en riesgo",Educación Secundaria,Desempleado con Subsidio de Desempleo,',
    // Familia 201 — esposa
    '2,201,10/01/2023,Fatima,Benali,F,611000002,X7482144M,Esposa,Marruecos,20/03/1983,,,,,,"Sin estudios",Personas Inactivas,',
    // Familia 202 — titular solo
    '3,202,05/03/2023,Amara,Diallo,M,622000001,Y8206459G,x,Senegal,01/01/1975,,,,,,Educación Primaria,Desempleado con Subsidio de Desempleo,',
    // Familia 203 — titular
    '4,203,12/06/2023,Ana,Rodríguez Pérez,F,633000001,AB123456,x,Colombia,22/09/1990,ana@test.es,"Av. Libertad 99",28010,Madrid,"Madre soltera",Educación Superior,Personas en situación de Precariedad Laboral,',
    // Familia 203 — hijo
    '5,203,12/06/2023,Lucas,Rodríguez Pérez,M,,,Hijo,Colombia,14/02/2015,,,,,,,,',
  ].join("\n");

  it("parses 3 families with 0 hard errors", () => {
    const { parseErrors } = transformCsv(REALISTIC_CSV);
    expect(parseErrors).toBe(0);
  });

  it("produces exactly 3 family groups", () => {
    const { groups } = transformCsv(REALISTIC_CSV);
    expect(groups).toHaveLength(3);
  });

  it("every group has exactly 1 titular and 0 group errors", () => {
    const { groups } = transformCsv(REALISTIC_CSV);
    for (const g of groups) {
      expect(g.errors).toHaveLength(0);
      const titulares = g.rows.filter((r) => r.is_titular);
      expect(titulares).toHaveLength(1);
    }
  });

  it("familia 201 has 2 members: titular (DNI) + esposa (NIE)", () => {
    const { groups } = transformCsv(REALISTIC_CSV);
    const fam201 = groups.find((g) => g.legacy_numero_familia === "201");
    expect(fam201).toBeDefined();
    expect(fam201!.rows).toHaveLength(2);
    expect(fam201!.rows[0].person.tipo_documento).toBe("DNI");
    expect(fam201!.rows[1].person.tipo_documento).toBe("NIE");
    expect(fam201!.rows[1].relacion_db).toBe("esposo_a");
  });

  it("familia 203 hijo is parsed with relacion_db = hijo_a", () => {
    const { groups } = transformCsv(REALISTIC_CSV);
    const fam203 = groups.find((g) => g.legacy_numero_familia === "203");
    expect(fam203).toBeDefined();
    expect(fam203!.rows).toHaveLength(2);
    const hijo = fam203!.rows.find((r) => !r.is_titular);
    expect(hijo!.relacion_db).toBe("hijo_a");
  });

  it("coerced situacion_laboral emits warnings but not hard errors", () => {
    const { groups, parseErrors } = transformCsv(REALISTIC_CSV);
    // 'Personas Inactivas' and 'Personas en situación de Precariedad Laboral'
    // are coerced — they produce RowWarnings but parseErrors must stay 0.
    expect(parseErrors).toBe(0);
    const fam201 = groups.find((g) => g.legacy_numero_familia === "201")!;
    const esposaWarnings = fam201.rows[1].warnings;
    const laboralWarning = esposaWarnings.find((w) => w.field === "situacion_laboral");
    expect(laboralWarning).toBeDefined();
    expect(laboralWarning!.code).toBe("laboral_unknown");
  });
});
