// ─── Country labels: ISO 3166-1 alpha-2 → display name (Spanish) ─────────────
// Ordered by frequency in Bocatas Digital user base
export const PAIS_LABELS: Record<string, string> = {
  ES: "España",
  MA: "Marruecos",
  SN: "Senegal",
  ML: "Mali",
  GN: "Guinea",
  GW: "Guinea-Bisáu",
  GM: "Gambia",
  NG: "Nigeria",
  GH: "Ghana",
  CM: "Camerún",
  CI: "Costa de Marfil",
  BF: "Burkina Faso",
  NE: "Níger",
  TG: "Togo",
  BJ: "Benín",
  CD: "Congo (RDC)",
  CG: "Congo",
  GA: "Gabón",
  MR: "Mauritania",
  DZ: "Argelia",
  TN: "Túnez",
  LY: "Libia",
  EG: "Egipto",
  SD: "Sudán",
  ET: "Etiopía",
  SO: "Somalia",
  ER: "Eritrea",
  PK: "Pakistán",
  BD: "Bangladés",
  IN: "India",
  CN: "China",
  PH: "Filipinas",
  RO: "Rumanía",
  UA: "Ucrania",
  RU: "Rusia",
  SY: "Siria",
  IQ: "Irak",
  AF: "Afganistán",
  CO: "Colombia",
  VE: "Venezuela",
  EC: "Ecuador",
  PE: "Perú",
  BO: "Bolivia",
  HN: "Honduras",
  GT: "Guatemala",
  SV: "El Salvador",
  DO: "República Dominicana",
  CU: "Cuba",
  BR: "Brasil",
  MX: "México",
  PT: "Portugal",
  FR: "Francia",
  IT: "Italia",
  DE: "Alemania",
  GB: "Reino Unido",
};

// ISO 3166-1 alpha-2 country codes for document origin
export const PAIS_DOCUMENTO_LABELS: Record<string, string> = {
  ES: "Espana",
  FR: "Francia",
  DE: "Alemania",
  IT: "Italia",
  PT: "Portugal",
  RO: "Rumania",
  BG: "Bulgaria",
  PL: "Polonia",
  UA: "Ucrania",
  MA: "Marruecos",
  SN: "Senegal",
  ML: "Mali",
  GH: "Ghana",
  NG: "Nigeria",
  CD: "Republica Democratica del Congo",
  CI: "Costa de Marfil",
  CM: "Camerun",
  GB: "Reino Unido",
  NL: "Paises Bajos",
  BE: "Belgica",
  CH: "Suiza",
  AT: "Austria",
  CZ: "Republica Checa",
  HU: "Hungria",
  GR: "Grecia",
  TR: "Turquia",
  SY: "Siria",
  AF: "Afganistan",
  PK: "Pakistan",
  IN: "India",
  BD: "Bangladesh",
  VN: "Vietnam",
  CN: "China",
  MX: "Mexico",
  CO: "Colombia",
  PE: "Peru",
  BO: "Bolivia",
  EC: "Ecuador",
  AR: "Argentina",
  CL: "Chile",
  PY: "Paraguay",
  UY: "Uruguay",
};
