// Single source of truth for informe-social freshness. Two RELATED concepts,
// both anchored to the same 6-month cadence (Leo, 2026-07-08):
//
//  A) SEGUIMIENTO gate (isInformeStale): how old the last follow-up (the
//     "review") may be for generation to be allowed. An informe must not be
//     produced off a review older than the informe's own validity → 6 months.
//     Server (documentService.validateContext), eligibility, and client
//     (SocialReportPanel blockingError) MUST agree — so it lives here.
//
//  B) INFORME DOCUMENT validity (informeDocStatus): once made, an informe is
//     valid for INFORME_EXPIRY_MONTHS and should be renewed by
//     INFORME_REVIEW_MONTHS. Drives the status badge, the list, and the bulk
//     "renew missing + stale" rule. Do NOT inline month comparisons elsewhere.

/** Months after which the informe should be reviewed/renewed ("por renovar"). */
export const INFORME_REVIEW_MONTHS = 5;
/** Months after which the informe is no longer valid ("vencido") — also the max
 *  age of the last seguimiento for generation to be allowed. */
export const INFORME_EXPIRY_MONTHS = 6;

export type InformeDocStatus = "sin_informe" | "al_dia" | "por_renovar" | "vencido";

/** Whole calendar months elapsed between an ISO date and `now` (default: today). */
export function monthsSince(fechaISO: string, nowMs: number = Date.now()): number {
  const then = new Date(`${fechaISO}T00:00:00`);
  const now = new Date(nowMs);
  let months =
    (now.getFullYear() - then.getFullYear()) * 12 + (now.getMonth() - then.getMonth());
  if (now.getDate() < then.getDate()) months -= 1; // not a full month yet
  return months;
}

/**
 * ISO (YYYY-MM-DD) date exactly `months` before `now`. Use for SQL cutoffs so
 * server-side renewal filters share the same threshold as the client status —
 * e.g. `informe_social_fecha < monthsAgoISO(INFORME_REVIEW_MONTHS)` selects the
 * families whose informe is due for renewal. No inline day counts anywhere.
 */
export function monthsAgoISO(months: number, nowMs: number = Date.now()): string {
  const d = new Date(nowMs);
  d.setMonth(d.getMonth() - months);
  return d.toISOString().slice(0, 10);
}

/**
 * True when the last follow-up (review) is too old for generation — older than
 * INFORME_EXPIRY_MONTHS (6 months).
 *
 * Callers must handle a missing date (null/empty) separately — a missing
 * seguimiento is a distinct condition ("sin seguimientos") from a stale one
 * ("vencido"). This assumes a valid ISO (YYYY-MM-DD) date string.
 */
export function isInformeStale(fecha: string): boolean {
  return monthsSince(fecha) >= INFORME_EXPIRY_MONTHS;
}

/**
 * Renewal status of an informe from its date (`informe_social_fecha`). A blank
 * date means no informe exists yet. Assumes a valid ISO (YYYY-MM-DD) string.
 */
export function informeDocStatus(
  fecha: string | null | undefined,
  nowMs: number = Date.now(),
): InformeDocStatus {
  if (fecha == null || fecha.trim() === "") return "sin_informe";
  const m = monthsSince(fecha, nowMs);
  if (m >= INFORME_EXPIRY_MONTHS) return "vencido";
  if (m >= INFORME_REVIEW_MONTHS) return "por_renovar";
  return "al_dia";
}

/**
 * True when the informe should be (re)generated by the bulk tool: no informe
 * yet, or it is due for review (≥5 months) / expired (≥6 months). Families that
 * are "al día" (< 5 months) are left untouched.
 */
export function informeNeedsRenewal(
  fecha: string | null | undefined,
  nowMs: number = Date.now(),
): boolean {
  return informeDocStatus(fecha, nowMs) !== "al_dia";
}
