/**
 * observacionesReviewer — reviews and reformulates the raw `persons.observaciones`
 * field (interviewer intake notes) into professional social-work language suitable
 * for inclusion in an official Informe de Valoración Social.
 *
 * Contract:
 *  - Input: raw free-text notes from the interviewer (may be informal, fragmented,
 *    or contain personal opinions).
 *  - Optional: structured context already covered by the compositor (family
 *    composition, origin, district) — when provided, the LLM is explicitly
 *    instructed NOT to repeat that information.
 *  - Output: a reformulated paragraph in professional, impersonal, third-person
 *    social-work language — OR null if the input is empty, too short to be useful,
 *    or contains nothing appropriate for an official document.
 *  - STRICT integrity (the 4 agreements as implicit baseline):
 *      1. Impeccable with words — only write what is explicitly stated; name things
 *         exactly as they appear in the notes (no vague filler like "el subsidio
 *         correspondiente" when the notes don't name the specific benefit).
 *      2. Don't take anything personally — impersonal, third-person prose only.
 *      3. Don't make assumptions — if a detail is not in the notes, omit it; never
 *         infer, generalise, or complete with plausible-sounding information.
 *      4. Always do your best — professional, precise, concise output.
 *  - RGPD Art.9: the LLM prompt explicitly forbids including health, legal status,
 *    migration history, or other Art.9 sensitive data in the output.
 *
 * This function is called server-side only (inside a tRPC procedure).
 */

import { invokeLLM } from "../_core/llm";

// ── ISO-2 → Spanish country name (mirrors narrativeComposer.ts) ──
const regionNames: Intl.DisplayNames | null = (() => {
  try {
    return new Intl.DisplayNames(["es"], { type: "region" });
  } catch {
    return null;
  }
})();

function paisEs(code: string | null | undefined): string | null {
  if (!code) return null;
  const up = code.toUpperCase();
  if (regionNames) {
    try {
      const n = regionNames.of(up);
      if (n && n !== up) return n;
    } catch {
      /* fall through */
    }
  }
  return up;
}

/** Structured fields already generated by the compositor — the reviewer must
 *  NOT repeat any of this information in the output. */
export type StructuredContext = {
  num_adultos: number | null;
  num_menores: number | null;
  pais_origen: string | null;
  distrito: string | null;
};

/**
 * The base system prompt embeds the 4 agreements as implicit behavioural rules —
 * without naming them — so the LLM produces precise, honest, assumption-free prose.
 *
 * Key principles woven in:
 *  • Impeccable with words: name every benefit, procedure, or support exactly as
 *    stated in the notes; never substitute with vague filler.
 *  • Don't make assumptions: if a detail is absent, omit it — never infer or
 *    complete with plausible-sounding information.
 *  • Don't take anything personally: strict third-person, impersonal register.
 *  • Always do your best: concise, professional, legally appropriate output.
 */
const BASE_SYSTEM_PROMPT = `Eres un trabajador social profesional que redacta informes de valoración social oficiales en España.

Tu tarea es revisar unas notas de observación internas escritas por un entrevistador y reformularlas en lenguaje profesional de trabajo social, adecuado para un documento oficial.

REGLAS ESTRICTAS:
1. SOLO reformula la información que ya está en el texto. NO inventes, NO inferas, NO añadas datos que no estén explícitamente en las notas.
2. Usa tercera persona impersonal y lenguaje técnico de trabajo social.
3. Elimina opiniones personales, juicios de valor, o lenguaje informal.
4. NO incluyas datos de salud, situación legal, historial migratorio, ni ningún dato especialmente sensible (RGPD Art.9) — si los hay en las notas, omítelos.
5. Si las notas no contienen información relevante para un informe social oficial, o son demasiado breves/vagas, devuelve null.
6. El resultado debe ser un párrafo conciso (máximo 3-4 frases), no una lista.
7. Si el resultado sería prácticamente idéntico a las notas originales (ya están bien redactadas), devuélvelas con mínimos ajustes de formato.
8. ESPECIFICIDAD OBLIGATORIA: nombra cada prestación, trámite o apoyo exactamente tal como aparece en las notas originales. Si las notas dicen "Renta Mínima Vital", escribe "Renta Mínima Vital" — nunca "el subsidio correspondiente", "la ayuda recibida" ni ninguna otra expresión vaga. Si las notas no especifican el nombre exacto, omite la referencia en lugar de generalizar con términos vagos o imprecisos.`;

/** Build the system prompt, injecting a deduplication block when structured
 *  context is available. This prevents the reviewer from repeating information
 *  already generated by the compositor (family composition, origin, district). */
function buildSystemPrompt(ctx: StructuredContext | undefined): string {
  if (!ctx) return BASE_SYSTEM_PROMPT;

  const adultos = ctx.num_adultos ?? 0;
  const menores = ctx.num_menores ?? 0;
  const pais = paisEs(ctx.pais_origen);
  const distrito = ctx.distrito;

  // Build a human-readable summary of what the compositor already covers.
  const coveredParts: string[] = [];

  if (adultos > 0 || menores > 0) {
    const adultosStr =
      adultos > 0 ? `${adultos} ${adultos === 1 ? "persona adulta" : "personas adultas"}` : null;
    const menoresStr =
      menores > 0 ? `${menores} ${menores === 1 ? "menor" : "menores"}` : null;
    const composicion = [adultosStr, menoresStr].filter(Boolean).join(" y ");
    coveredParts.push(`composición familiar (${composicion})`);
  }

  if (pais) {
    coveredParts.push(`país de origen (${pais})`);
  }

  if (distrito) {
    coveredParts.push(`distrito de residencia (${distrito})`);
  }

  if (coveredParts.length === 0) return BASE_SYSTEM_PROMPT;

  const coveredList = coveredParts.join(", ");

  const dedupBlock = `
9. INFORMACIÓN YA CUBIERTA — NO repitas en tu respuesta la siguiente información, porque ya está cubierta por el texto estructurado del informe: ${coveredList}. Céntrate ÚNICAMENTE en información adicional que NO esté ya cubierta: circunstancias específicas, procesos en curso, deudas, apoyos recibidos, dinámicas familiares relevantes, etc.`;

  return BASE_SYSTEM_PROMPT + dedupBlock;
}

const RESPONSE_SCHEMA = {
  type: "json_schema" as const,
  json_schema: {
    name: "observaciones_review",
    strict: true,
    schema: {
      type: "object",
      properties: {
        texto_revisado: {
          type: ["string", "null"] as unknown as "string",
          description:
            "Texto reformulado en lenguaje profesional de trabajo social, o null si no hay contenido apto para el informe.",
        },
      },
      required: ["texto_revisado"],
      additionalProperties: false,
    },
  },
};

/**
 * reviewObservaciones — reformulates raw intake notes into professional social-work
 * language. Returns null if the input is empty or contains nothing suitable for an
 * official document.
 *
 * @param rawObservaciones - The raw `persons.observaciones` text.
 * @param structuredContext - Optional: fields already covered by the compositor.
 *   When provided, the LLM is instructed NOT to repeat family composition, origin,
 *   or district — preventing text duplication in the informe social.
 * @returns Reformulated text, or null.
 */
export async function reviewObservaciones(
  rawObservaciones: string | null | undefined,
  structuredContext?: StructuredContext,
): Promise<string | null> {
  const trimmed = (rawObservaciones ?? "").trim();
  if (!trimmed || trimmed.length < 10) return null;

  try {
    const systemPrompt = buildSystemPrompt(structuredContext);

    const res = await invokeLLM({
      messages: [
        { role: "system", content: systemPrompt },
        {
          role: "user",
          content: `Notas de observación a revisar:\n\n${trimmed}`,
        },
      ],
      response_format: RESPONSE_SCHEMA,
    });

    const rawContent = res.choices?.[0]?.message?.content;
    const raw = typeof rawContent === "string" ? rawContent : null;
    if (!raw) return null;

    const parsed = JSON.parse(raw) as { texto_revisado: string | null };
    const result = parsed.texto_revisado?.trim() ?? null;
    return result && result.length > 0 ? result : null;
  } catch {
    // LLM errors must never block informe generation — fall back to null (omit block).
    return null;
  }
}
