-- Migration: 20260723000002_create_family_documents_bucket.sql
--
-- Creates the `family-documents` storage bucket.
--
-- This bucket stores:
--   • Rendered informe_valoracion_social .docx files (generated by renderDocument)
--   • Signed actas from delivery rounds
--   • Any other family-level private documents
--
-- All server-side reads/writes use createAdminClient() (service role, bypasses RLS).
-- Authenticated users (admin/superadmin) can upload and read via signed URLs
-- generated server-side.
--
-- NOTE: This bucket was documented as "must be created separately" in migration
-- 20260430000002. This migration formalises that step.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'family-documents',
  'family-documents',
  false,
  52428800,  -- 50 MB max (PDFs, DOCX, images)
  ARRAY[
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/pdf',
    'image/jpeg',
    'image/png',
    'image/webp',
    'application/octet-stream'
  ]
)
ON CONFLICT (id) DO NOTHING;

-- Admin and superadmin can read (download via signed URL) and write (upload).
-- All actual access is done server-side via service role, so these policies are
-- a defence-in-depth layer only.
CREATE POLICY family_documents_bucket_admin_all
  ON storage.objects FOR ALL
  TO authenticated
  USING   (bucket_id = 'family-documents' AND public.get_user_role() IN ('admin', 'superadmin'))
  WITH CHECK (bucket_id = 'family-documents' AND public.get_user_role() IN ('admin', 'superadmin'));
