-- 20260707000007_deliveries_registrado_por_to_text.sql
-- TES-04 (#116): align deliveries.registrado_por with production.
--
-- Prod state (verified 2026-07-07 via information_schema/pg_policies):
--   registrado_por is `text`, has NO FK to auth.users, and policy
--   deliveries_voluntario_insert compares `registrado_por = (auth.uid())::text`.
--
-- Repo state on a clean `db reset`: the earliest create
--   (20260411081841_..._create_deliveries.sql) wins with
--   `registrado_por uuid REFERENCES auth.users(id)`; the later v2 creates declare
--   TEXT but use CREATE TABLE IF NOT EXISTS, so they no-op. entregas.create writes
--   a Manus user id (a non-UUID string) into registrado_por, which raises 22P02
--   against a uuid column in CI/new-dev environments. This migration makes a clean
--   reset match prod. See ADR-0011 (user-identity columns are TEXT under Manus OAuth).

BEGIN;

-- The voluntario INSERT policy references registrado_por in WITH CHECK, so it
-- blocks ALTER COLUMN TYPE. Drop it, change the type, recreate with the
-- (auth.uid())::text cast that prod uses.
DROP POLICY IF EXISTS deliveries_voluntario_insert ON public.deliveries;

-- Manus user ids are non-UUID strings, so registrado_por cannot FK auth.users.
-- Prod already dropped this constraint; drop it here for parity (name is the
-- inline-REFERENCES autogenerated one from 20260411081841_..._create_deliveries.sql).
ALTER TABLE public.deliveries DROP CONSTRAINT IF EXISTS deliveries_registrado_por_fkey;

-- uuid -> text. Idempotent: re-running where already text is a no-op cast.
ALTER TABLE public.deliveries ALTER COLUMN registrado_por TYPE text USING registrado_por::text;

-- Recreate the voluntario insert policy to match prod (text = text via cast).
CREATE POLICY deliveries_voluntario_insert ON public.deliveries
  FOR INSERT TO authenticated
  WITH CHECK (
    public.get_user_role() = 'voluntario'
    AND registrado_por = (auth.uid())::text
  );

COMMIT;
